-- 코드를 입력하세요
SELECT FOOD_TYPE
     , REST_ID
     , REST_NAME
     , FAVORITES
FROM REST_INFO A
INNER JOIN (SELECT MAX(FAVORITES) AS FAVORITE FROM REST_INFO GROUP BY FOOD_TYPE) B
ON A.FAVORITES = B.FAVORITE
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC