-- 코드를 입력하세요
SELECT A.USER_ID
     , A.NICKNAME
     , A.TOTAL_SALES
FROM (SELECT SB.USER_ID
           , SB.NICKNAME
           , SUM(SA.PRICE) AS TOTAL_SALES
        FROM USED_GOODS_BOARD SA
        INNER JOIN USED_GOODS_USER SB
               ON SA.WRITER_ID = SB.USER_ID
              AND SA.STATUS = 'DONE'
        GROUP BY SA.WRITER_ID
      ) A
WHERE A.TOTAL_SALES >= 700000
ORDER BY A.TOTAL_SALES ASC